<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>pl.kiosel.playerlist</groupId>
        <artifactId>advancedplayerlist-parent</artifactId>
        <version>1.2.2</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>advancedplayerlist-bukkit</artifactId>
    <packaging>jar</packaging>

    <name>AdvancedPlayerList</name>

    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/Kitosel/AdvancedPlayerList</url>
        </repository>
    </distributionManagement>

    <build>
        <finalName>${project.name}-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.1</version>
                <executions>
                    <execution>
                        <id>bridge-protocol-source</id>
                        <phase>generate-sources</phase>
                        <goals><goal>add-source</goal></goals>
                        <configuration>
                            <sources>
                                <source>${project.parent.basedir}/proxy/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <release>8</release>
                    <excludes>
                        <exclude>pl/kiosel/playerlist/bridge/proxy/**</exclude>
                    </excludes>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.2.5</version>
			</plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										<exclude>META-INF/MANIFEST.MF</exclude>
										<exclude>META-INF/*.SF</exclude>
										<exclude>META-INF/*.DSA</exclude>
										<exclude>META-INF/*.RSA</exclude>
										<exclude>META-INF/maven/**</exclude>
									</excludes>
								</filter>
                                <filter>
                                    <artifact>org.json:json</artifact>
                                    <excludes>
                                        <exclude>META-INF/MANIFEST.MF</exclude>
                                    </excludes>
                                </filter>

                                <filter>
                                    <artifact>pl.kiosel.rosacore:rosacore-platform-bukkit</artifact>
                                    <excludeDefaults>false</excludeDefaults>
                                    <excludes>
                                        <exclude>**/dependencies/nbtapi/**</exclude>
                                        <exclude>**/dependencies/hikari/**</exclude>
                                    </excludes>
                                </filter>

                            </filters>
                            <relocations>
                                <relocation>
                                    <pattern>org.json</pattern>
									<shadedPattern>pl.kiosel.playerlist.dependencies.json</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>pl.kiosel.rosacore</pattern>
                                    <shadedPattern>pl.kiosel.playerlist.core</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
			<artifactId>spigot-api</artifactId>
			<version>${spigot-api.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>pl.kiosel.rosacore</groupId>
            <artifactId>rosacore-platform-bukkit</artifactId>
			<version>0.2.2</version>
            <scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-nop</artifactId>
				</exclusion>
			</exclusions>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20231013</version>
            <scope>compile</scope>
        </dependency>

        <!-- API -->
        <dependency>
            <groupId>pl.kiosel.playerlist</groupId>
            <artifactId>advancedplayerlist-proxy</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.12.3</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.1.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

	<profiles>
		<profile>
			<id>modern-java-script-tests</id>
			<activation>
				<jdk>[12,)</jdk>
			</activation>
			<dependencies>
				<dependency>
					<groupId>org.openjdk.nashorn</groupId>
					<artifactId>nashorn-core</artifactId>
					<version>15.6</version>
					<scope>test</scope>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
</project>
